name: wpp_au
description: wpp_au package
version: 0.0.1
homepage: https://example.com
repository: https://example.com

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  dart_jsonwebtoken: ^2.6.1
  jwt_decode: ^0.3.1
  rounded_loading_button: ^2.1.0
  http: ^0.13.5
  intl: ^0.18.0
  platform_device_id: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
