Map<String, String> zh() {
  return {
    "continueStr": "继续",
    "anonimT1": "使用匿名帐户继续。你叫什么名字？",
    "anonimCon": "继续匿名登录",
    "changeMailSuccess": "成功！请检查您的电子邮件收件箱。确认码通常在2分钟内发送。 （还请检查您的垃圾邮件文件夹。）",
    "demoUserEnterMail": "请输入您的电子邮件地址。 （将发送确认码。）",
    "mail": "您的电子邮件地址",
    "createWp": "创建 Wipepp 帐户",
    "min5": "密码长度至少为6个字符。",
    "invalidPass": "无效的密码。请重试或点击“忘记密码”重置密码。",
    "wppAu1": "使用您的 Wippe 帐户。如果您还没有帐户，将创建一个新帐户。",
    "wppAu2": "首先，请输入您的电子邮件地址。",
    "wppAu3": "更多信息。",
    "next": "下一步",
    "showPass": "显示密码。",
    "notEmptyText": "必填字段。请填写。",
    "login": "登录",
    "email": "输入您的电子邮件",
    "pass": "输入您的密码",
    "forget": "忘记密码？",
    "login_have": "还没有帐户？注册",
    "signup": "注册",
    "new_pass": "创建密码",
    "re_new_pass": "确认您的密码",
    "signup_have": "已经有帐户？登录",
    "name": "输入您的姓名",
    "year": "年龄",
    "year_data": "输入您的出生日期",
    "back": "返回",
    "forget_enter_mail": "在下面的字段中键入您的电子邮件地址。",
    "forget_b1": "发送密码重置请求",
    "fill": "填写必填字段。",
    "not_c": "电子邮件和/或密码不正确。请检查准确性。",
    "wp_token_error": "请重试或使用电子邮件登录。",
    "pass_re_w": "您在密码确认中犯了一个错误。您输入的两个密码必须相同。",
    "forget_p_success": "您的密码更改请求已发送到您的电子邮件地址。检查您的电子邮件邮箱。 （还请检查您的垃圾邮件文件夹。）",
    "send": "发送",
    "verifier_T1": "在下面输入发送到您的电子邮件地址的确认码。",
    "verifier_B1": "重新发送验证代码",
    "change_email_T1": "这个电子邮件地址不属于您吗？更改您的电子邮件地址。",
    "change_email_B1": "更改电子邮件地址",
    "verifier_code": "输入确认码",
    "enter_new_email": "输入您的新电子邮件地址",
    "verify_acc": "验证帐户",
    "v_c_err": "验证码不正确。",
    "login_again_c_pass": "重新登录。密码已更改。",
    "again_code": "检查您的电子邮件邮箱。 （还请检查您的垃圾邮件文件夹。）",
    "err_again_code_limit": "您已发出太多请求。请在1小时后重试。",
    "year_warn": "您必须年满13岁或更大才能使用该应用程序并创建帐户。",
    "usertrue": "使用此电子邮件地址已存在帐户。请登录。如果您忘记密码，请点击“我忘记了密码”按钮。",
  };
}
